version: '3'


services:

  app:
    build: .
    restart: unless-stopped
    command: /bin/bash -c "poetry run python manage.py collectstatic --noinput && poetry run python manage.py migrate && poetry run uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    network_mode: 'host'

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.conf.template
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/code/static
      - media_volume:/code/media
    command: bash -c "envsubst '$${HOST}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - .env
    environment:
      - HOST=${HOST}
    depends_on:
      - app
    network_mode: 'host'



volumes:
  static_volume:
  media_volume:

