# Generated by Django 5.0.7 on 2024-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Показать на главной'),
        ),
    ]
