# Generated by Django 5.0.7 on 2024-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_teacher_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('teacher', 'Наставник'), ('lesson', 'Занятие'), ('study', 'Учеников')], error_messages={'unique': 'Такая статистика уже есть на сайте'}, max_length=20, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=10, verbose_name='Значение статистики')),
                ('is_display', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
